// Stub class source file generated by jrmi-compiler, do not edit it

package edu.cmu.courses.rmi.registry;

import edu.cmu.courses.rmi.Registry;

public final class RegistryImpl_Stub
        extends edu.cmu.courses.rmi.RemoteStub
        implements Registry
{

    private static java.lang.reflect.Method $method_bind_0;
    private static java.lang.reflect.Method $method_unbind_1;
    private static java.lang.reflect.Method $method_lookup_2;
    private static java.lang.reflect.Method $method_list_3;
    private static java.lang.reflect.Method $method_rebind_4;
    static {
        try {
            $method_bind_0 = Registry.class.getMethod("bind", new java.lang.Class[] {java.lang.String.class, edu.cmu.courses.rmi.RemoteRef.class});
            $method_unbind_1 = Registry.class.getMethod("unbind", new java.lang.Class[] {java.lang.String.class});
            $method_lookup_2 = Registry.class.getMethod("lookup", new java.lang.Class[] {java.lang.String.class});
            $method_list_3 = Registry.class.getMethod("list", new java.lang.Class[] {});
            $method_rebind_4 = Registry.class.getMethod("rebind", new java.lang.Class[] {java.lang.String.class, edu.cmu.courses.rmi.RemoteRef.class});
        } catch (java.lang.NoSuchMethodException e) {
            throw new java.lang.NoSuchMethodError("stub class initialization failed");
        }
    }

    public RegistryImpl_Stub() {
        super();
    }
    public RegistryImpl_Stub(edu.cmu.courses.rmi.RemoteRef ref) {
        super(ref);
    }


    public void bind(java.lang.String $param_0, edu.cmu.courses.rmi.RemoteRef $param_1)
            throws edu.cmu.courses.rmi.exceptions.RemoteException, edu.cmu.courses.rmi.exceptions.AlreadyBoundException {
        invoke($method_bind_0, new java.lang.Object[] {$param_0, $param_1});
    }

    public void unbind(java.lang.String $param_0)
            throws edu.cmu.courses.rmi.exceptions.RemoteException, edu.cmu.courses.rmi.exceptions.NotBoundException {
        invoke($method_unbind_1, new java.lang.Object[] {$param_0});
    }

    public edu.cmu.courses.rmi.RemoteRef lookup(java.lang.String $param_0)
            throws edu.cmu.courses.rmi.exceptions.RemoteException {
        Object $result = invoke($method_lookup_2, new java.lang.Object[] {$param_0});
        return (edu.cmu.courses.rmi.RemoteRef)$result;
    }

    public java.lang.String[] list()
            throws edu.cmu.courses.rmi.exceptions.RemoteException {
        Object $result = invoke($method_list_3, null);
        return (java.lang.String[])$result;
    }

    public void rebind(java.lang.String $param_0, edu.cmu.courses.rmi.RemoteRef $param_1)
            throws edu.cmu.courses.rmi.exceptions.RemoteException {
        invoke($method_rebind_4, new java.lang.Object[] {$param_0, $param_1});
    }
}