// Stub class source file generated by jrmi-compiler, do not edit it

package edu.cmu.courses.rmiexample.server;

public final class HelloWorldImpl_Stub
    extends edu.cmu.courses.rmi.RemoteStub
    implements edu.cmu.courses.rmiexample.common.HelloWorld
{
    
    private static java.lang.reflect.Method $method_sayHello_0;
    static {
	    try {
		    $method_sayHello_0 = edu.cmu.courses.rmiexample.common.HelloWorld.class.getMethod("sayHello", new java.lang.Class[] {});
		} catch (java.lang.NoSuchMethodException e) {
			throw new java.lang.NoSuchMethodError("stub class initialization failed");
		}
	}
	
	public HelloWorldImpl_Stub() {
	    super();
	}
	public HelloWorldImpl_Stub(edu.cmu.courses.rmi.RemoteRef ref) {
	    super(ref);
	}
	
	
	public void sayHello()
		    throws edu.cmu.courses.rmi.exceptions.RemoteException {
		invoke($method_sayHello_0, null);
	}
}
